### ISSUE TITLE
npm run integration error

### ISSUE THREAD

**Issue by andrea-spotsoftware** [anjmao/ang-select#5]
Hello @anjmao,
i have some freetime now and i'm trying your library seed.
I've noticed that integration tests are failing, looks like a configuration error

This is the console log:
```
C:\Users\a.corzani\Documents\ang-select>npm run integration

> ang-select@1.0.0 preintegration C:\Users\a.corzani\Documents\ang-select
> npm run clean && npm run build && cd integration && npm install


> ang-select@1.0.0 clean C:\Users\a.corzani\Documents\ang-select
> rimraf out-tsc dist/*


> ang-select@1.0.0 prebuild C:\Users\a.corzani\Documents\ang-select
> npm run clean


> ang-select@1.0.0 clean C:\Users\a.corzani\Documents\ang-select
> rimraf out-tsc dist/*


> ang-select@1.0.0 build C:\Users\a.corzani\Documents\ang-select
> node build.js

Inlining succeeded.
ES2015 compilation succeeded.
ES5 compilation succeeded.
Typings and metadata copy succeeded.
All bundles generated successfully.
Package files copy succeeded.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arc
h":"x64"})

> ang-select@1.0.0 integration C:\Users\a.corzani\Documents\ang-select
> npm run integration:aot && npm run integration:jit


> ang-select@1.0.0 integration:aot C:\Users\a.corzani\Documents\ang-select
> cd integration && npm run e2e:aot


> integration-test@1.0.0 pree2e:aot C:\Users\a.corzani\Documents\ang-select\integration
> npm run build:e2e && npm run build:aot


> integration-test@1.0.0 build:e2e C:\Users\a.corzani\Documents\ang-select\integration
> tsc -p e2e/


> integration-test@1.0.0 build:aot C:\Users\a.corzani\Documents\ang-select\integration
> node build.js

Error at C:/Users/a.corzani/Documents/ang-select/integration/out-tsc/node_modules/ang-select/ang-select.ngfactory.ts:250:44: Property 'viewPortItems' d
oes not exist on type 'AngSelectComponent'.
Error at C:/Users/a.corzani/Documents/ang-select/integration/out-tsc/node_modules/ang-select/ang-select.ngfactory.ts:275:35: Property 'filteredItems' i
s private and only accessible within class 'AngSelectComponent'.
Error at C:/Users/a.corzani/Documents/ang-select/integration/out-tsc/node_modules/ang-select/ang-select.ngfactory.ts:278:35: Property 'viewPortItems' d
oes not exist on type 'AngSelectComponent'.
Error at C:/Users/a.corzani/Documents/ang-select/integration/out-tsc/node_modules/ang-select/ang-select.ngfactory.ts:280:36: Property 'filteredItems' i
s private and only accessible within class 'AngSelectComponent'.
(node:12688) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not resolve '../out-tsc/src/app/app.module.n
gfactory' from C:\Users\a.corzani\Documents\ang-select\integration\src\main-aot.js

> integration-test@1.0.0 e2e:aot C:\Users\a.corzani\Documents\ang-select\integration
> concurrently "npm run serve:e2e-aot" "npm run protractor" --kill-others --success first

[1]
[1] > integration-test@1.0.0 preprotractor C:\Users\a.corzani\Documents\ang-select\integration
[1] > webdriver-manager update
[1]
[0]
[0] > integration-test@1.0.0 serve:e2e-aot C:\Users\a.corzani\Documents\ang-select\integration
[0] > lite-server -c bs-config.e2e-aot.json
[0]
[1] [12:37:04] I/update - chromedriver: file exists C:\Users\a.corzani\Documents\ang-select\integration\node_modules\protractor\node_modules\webdriver-
manager\selenium\chromedriver_2.31.zip
[1] [12:37:04] I/update - chromedriver: unzipping chromedriver_2.31.zip
[1] [12:37:05] I/update - chromedriver: chromedriver_2.31.exe up to date
[1] [12:37:05] I/update - selenium standalone: file exists C:\Users\a.corzani\Documents\ang-select\integration\node_modules\protractor\node_modules\web
driver-manager\selenium\selenium-server-standalone-3.5.0.jar
[1] [12:37:05] I/update - selenium standalone: selenium-server-standalone-3.5.0.jar up to date
[1] [12:37:06] I/update - geckodriver: file exists C:\Users\a.corzani\Documents\ang-select\integration\node_modules\protractor\node_modules\webdriver-m
anager\selenium\geckodriver-v0.18.0.zip
[1] [12:37:06] I/update - geckodriver: unzipping geckodriver-v0.18.0.zip
[1] [12:37:06] I/update - geckodriver: geckodriver-v0.18.0.exe up to date
[1]
[1] > integration-test@1.0.0 protractor C:\Users\a.corzani\Documents\ang-select\integration
[1] > protractor protractor.config.js
[1]
[1] [12:37:07] I/launcher - Running 1 instances of WebDriver
[1] [12:37:07] I/direct - Using ChromeDriver directly...
[1] Started
[1]
[1] [12:37:19] E/protractor - Could not find Angular on page http://localhost:8080/ : retries looking for angular exceeded
[1] F
[1]
[1]
[1] Failures:
[1] 1) AngSelect Lib E2E Tests should display lib
[1]   Message:
[1]     Failed: Angular could not be found on the page http://localhost:8080/.If this is not an Angular application, you may need to turn off waiting f
or Angular.
[1]                               Please see
[1]                               https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
[1]   Stack:
[1]     Error: Angular could not be found on the page http://localhost:8080/.If this is not an Angular application, you may need to turn off waiting fo
r Angular.
[1]                               Please see
[1]                               https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
[1]         at executeAsyncScript_.then (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\protractor\lib\browser.ts:936:29)
[1]         at ManagedPromise.invokeCallback_ (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:1366:
14)
[1]         at TaskQueue.execute_ (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:2970:14)
[1]         at TaskQueue.executeNext_ (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:2953:27)
[1]         at asyncRun (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:2813:27)
[1]         at C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:676:7
[1]         at process._tickCallback (internal/process/next_tick.js:109:7)
[1]     From: Task: Run beforeEach in control flow
[1]         at UserContext.<anonymous> (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\jasminewd2\index.js:94:19)
[1]     From asynchronous test:
[1]     Error
[1]         at Suite.<anonymous> (C:\Users\a.corzani\Documents\ang-select\integration\e2e\app.e2e-spec.ts:5:3)
[1]         at Object.<anonymous> (C:\Users\a.corzani\Documents\ang-select\integration\e2e\app.e2e-spec.ts:3:1)
[1]         at Module._compile (module.js:570:32)
[1]         at Object.Module._extensions..js (module.js:579:10)
[1]         at Module.load (module.js:487:32)
[1]         at tryModuleLoad (module.js:446:12)
[1]   Message:
[1]     Failed: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-ang
ular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for detai
ls"
[1]   Stack:
[1]     Error: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angu
lar page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for detail
s"
[1]         at runWaitForAngularScript.then (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\protractor\lib\browser.ts:653:19)
[1]         at ManagedPromise.invokeCallback_ (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:1366:
14)
[1]         at TaskQueue.execute_ (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:2970:14)
[1]         at TaskQueue.executeNext_ (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:2953:27)
[1]         at asyncRun (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:2813:27)
[1]         at C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:676:7
[1]         at process._tickCallback (internal/process/next_tick.js:109:7)Error
[1]         at ElementArrayFinder.applyAction_ (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\protractor\lib\element.ts:482:23)
[1]         at ElementArrayFinder.(anonymous function) [as getText] (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\protractor\lib\el
ement.ts:96:21)
[1]         at ElementFinder.(anonymous function) [as getText] (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\protractor\lib\element
.ts:873:14)
[1]         at UserContext.<anonymous> (C:\Users\a.corzani\Documents\ang-select\integration\e2e\app.e2e-spec.ts:14:34)
[1]         at C:\Users\a.corzani\Documents\ang-select\integration\node_modules\jasminewd2\index.js:112:25
[1]         at new ManagedPromise (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:1067:7)
[1]         at ControlFlow.promise (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:2396:12)
[1]         at schedulerExecute (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\jasminewd2\index.js:95:18)
[1]         at TaskQueue.execute_ (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:2970:14)
[1]         at TaskQueue.executeNext_ (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:2953:27)
[1]     From: Task: Run it("should display lib") in control flow
[1]         at UserContext.<anonymous> (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\jasminewd2\index.js:94:19)
[1]         at C:\Users\a.corzani\Documents\ang-select\integration\node_modules\jasminewd2\index.js:64:48
[1]         at ControlFlow.emit (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\events.js:62:21)
[1]         at ControlFlow.shutdown_ (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:2565:10)
[1]     From asynchronous test:
[1]     Error
[1]         at Suite.<anonymous> (C:\Users\a.corzani\Documents\ang-select\integration\e2e\app.e2e-spec.ts:13:3)
[1]         at Object.<anonymous> (C:\Users\a.corzani\Documents\ang-select\integration\e2e\app.e2e-spec.ts:3:1)
[1]         at Module._compile (module.js:570:32)
[1]         at Object.Module._extensions..js (module.js:579:10)
[1]         at Module.load (module.js:487:32)
[1]         at tryModuleLoad (module.js:446:12)
[1]   Message:
[1]     Expected [ Entry({ level: SEVERE, message: 'http://localhost:8080/bundle.js - Failed to load resource: the server responded with a status of 40
4 (Not Found)', timestamp: 1502447829702, type: '' }), Entry({ level: SEVERE, message: 'http://localhost:8080/bundle.js - Failed to load resource: the
server responded with a status of 404 (Not Found)', timestamp: 1502447829709, type: '' }) ] to equal [  ].
[1]
[1]   Stack:
[1]     Error: Failed expectation
[1]         at C:\Users\a.corzani\Documents\ang-select\integration\e2e\app.e2e-spec.ts:9:26
[1]         at ManagedPromise.invokeCallback_ (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:1366:
14)
[1]         at TaskQueue.execute_ (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:2970:14)
[1]         at TaskQueue.executeNext_ (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:2953:27)
[1]         at asyncRun (C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:2813:27)
[1]         at C:\Users\a.corzani\Documents\ang-select\integration\node_modules\selenium-webdriver\lib\promise.js:676:7
[1]         at process._tickCallback (internal/process/next_tick.js:109:7)
[1]
[1] 1 spec, 1 failure
[1] Finished in 10.399 seconds
[1]
[1] [12:37:20] I/launcher - 0 instance(s) of WebDriver still running
[1] [12:37:20] I/launcher - chrome #01 failed 1 test(s)
[1] [12:37:20] I/launcher - overall: 1 failed spec(s)
[1] [12:37:20] E/launcher - Process exited with error code 1
[1]
[1] npm
[1]  ERR! Windows_NT 6.3.9600
[1] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\a.corzani\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "protra
ctor"
[1] npm ERR! node v6.11.2
[1] npm ERR! npm  v3.10.8
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! integration-test@1.0.0 protractor: `protractor protractor.config.js`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the integration-test@1.0.0 protractor script 'protractor protractor.config.js'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the integration-test package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     protractor protractor.config.js
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs integration-test
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls integration-test
[1] npm ERR! There is likely additional logging output above.
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     C:\Users\a.corzani\Documents\ang-select\integration\npm-debug.log
[1] npm run protractor exited with code 1
--> Sending SIGTERM to other processes..
[0] npm run serve:e2e-aot exited with code 1

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\a.corzani\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "e2e:aot"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! integration-test@1.0.0 e2e:aot: `concurrently "npm run serve:e2e-aot" "npm run protractor" --kill-others --success first`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integration-test@1.0.0 e2e:aot script 'concurrently "npm run serve:e2e-aot" "npm run protractor" --kill-others --success first'.

npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the integration-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run serve:e2e-aot" "npm run protractor" --kill-others --success first
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs integration-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls integration-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\a.corzani\Documents\ang-select\integration\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\a.corzani\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "integratio
n:aot"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ang-select@1.0.0 integration:aot: `cd integration && npm run e2e:aot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ang-select@1.0.0 integration:aot script 'cd integration && npm run e2e:aot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ang-select package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd integration && npm run e2e:aot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ang-select
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ang-select
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\a.corzani\Documents\ang-select\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\a.corzani\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "integratio
n"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ang-select@1.0.0 integration: `npm run integration:aot && npm run integration:jit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ang-select@1.0.0 integration script 'npm run integration:aot && npm run integration:jit'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ang-select package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run integration:aot && npm run integration:jit
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ang-select
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ang-select
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\a.corzani\Documents\ang-select\npm-debug.log
```

Is it working on a clean install on your environment? I'm trying on master branch.

**Comment by anjmao** [comment]
Hi @andrea-spotsoftware for now I removed integration project at all because I'm planning to use angular-cli for integrations tests. I added this to my roadmap, but first I want to implement all needed features for first alpha release.
